// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQTNLhJ64CxfHRNtT8KeMRyzaDsx8hh8I',
    appId: '1:486730364237:web:48f517767ddd0a41df7304',
    messagingSenderId: '486730364237',
    projectId: 'sas-telkom',
    authDomain: 'sas-telkom.firebaseapp.com',
    storageBucket: 'sas-telkom.firebasestorage.app',
    measurementId: 'G-9SLRRDSP4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBQhRDI3iGbFsbKdVU1e6ubpH1mQwBwnk',
    appId: '1:486730364237:android:bbe8144c78cb3523df7304',
    messagingSenderId: '486730364237',
    projectId: 'sas-telkom',
    storageBucket: 'sas-telkom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsRlvWhlae8_ZOnbwy2moymycob_jbULs',
    appId: '1:486730364237:ios:8a84480f3d6ca865df7304',
    messagingSenderId: '486730364237',
    projectId: 'sas-telkom',
    storageBucket: 'sas-telkom.firebasestorage.app',
    iosBundleId: 'com.example.sas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsRlvWhlae8_ZOnbwy2moymycob_jbULs',
    appId: '1:486730364237:ios:8a84480f3d6ca865df7304',
    messagingSenderId: '486730364237',
    projectId: 'sas-telkom',
    storageBucket: 'sas-telkom.firebasestorage.app',
    iosBundleId: 'com.example.sas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQTNLhJ64CxfHRNtT8KeMRyzaDsx8hh8I',
    appId: '1:486730364237:web:ec62c15f356bc537df7304',
    messagingSenderId: '486730364237',
    projectId: 'sas-telkom',
    authDomain: 'sas-telkom.firebaseapp.com',
    storageBucket: 'sas-telkom.firebasestorage.app',
    measurementId: 'G-2VL6DX9TPY',
  );
}
